print("Hello World")
print("Sidra")
print("Sidra Anwaar")
print("Hi, I am Python.")
print(25)
print(2*2)
print(2+5+9)
print("Hello, ","I ","am ","Sidra. ")
print("Sidra ","is ",20, " Years ","old.")
print(5,"+",3,"=",5+3)